# -*- coding: utf-8 -*-
"""Copy of ML_EXP2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T35MWSqztJ0uoURAIZhxK5XWlQ22Wl6u
"""

import numpy as np
import pandas as pd

df = pd.read_csv('exp2.csv.csv')
n_row = df.shape[0]

li = []
for i in range(n_row):
    li.append(1)

df.insert(0,"X0", li, True)  
print(df)

main_matrix = df.to_numpy()

print(main_matrix)

n_col = df.shape[1]

result = np.hsplit(main_matrix, [n_col-1,n_col]) 
X = result[0]
Y = result[1]

print(X)
print(Y)

X_T = X.transpose()
print(X_T)

X_T_X = np.matmul(X_T,X)
print(X_T_X)

inv = np.linalg.inv(X_T_X)
print(inv)

inv_T = np.matmul(inv, X_T)
print(inv_T)

answer = np.matmul(inv_T, Y)
print(answer)

temp = ""
for i in range(1,n_col-1):
  if answer[i][0]<0:
    temp += " - "+str(-answer[i][0])+" X"+str(i)
  else:
    temp += " + "+str(answer[i][0])+" X"+str(i)
print("Y = "+ str(answer[0][0])+temp)

